### PR TITLE
Updated to swift 2.0, and fixed compiler warnings

### PR DESCRIPTION
**Pull request by ryancrosby**
I updated this to Swift 2.0, and fixed a couple new compiler warnings in the process. Hopefully this will work, or at least get you started.

### CODE REVIEW

**Comment by RomuloVitoi** [comment]
+1

**Comment by JasperMeurs** [comment]
+1

**Comment by ryancrosby** [comment]
As we wait for this to get merged in, my fork can be used just by adding this to your Podfile.  
 `pod 'UIColor-Hex-Swift', :git => 'git@github.com:ryancrosby/UIColor-Hex-Swift.git'`

**Comment by frederik-jacques** [comment]
Thanks alot @ryancrosby for your work.
Sorry, it took some time to approve the PR, it seems I didn't get notified from Github that there was a PR waiting :)

**Pull request merged**
